#!/bin/bash
set -e

#Ajout des instructions pour le labo
echo "Ajout des instructions pour le labo"
echo "Static  : $STATIC_APP"
echo "Dynamic : $DYNAMIC_APP"

# Apache gets grumpy about PID files pre-existing
rm -f /var/run/apache2/apache2.pid

exec apache2 -DFOREGROUND
