FROM php:5.6-apache
COPY src/ /var/www/html/

#start docker daemon
#eval "$(docker-machine env default)"

#lancer le container avec un mapping du port 80
#de la vm vers le port 9090 de l'host
#docker run -d -p 9090:80 php:5.6-apache

#docker ps pour lister les container en cours

#ip de la docker machine : 192.168.99.100

#lancer un bash du container
#docker exec -it nom_du_container /bin/bash

#stopper un container
#docker kill nom_du_container

#le container s'appelle res/apache-php
#docker build -t res/apache-php .

#docker run -d -p 9090:80 res/apache-php

#location de apache
#/etc/apache2/

#configuration actuelle
#/etc/apache2/sites-available

#location des sources
#/var/www/html/
