FROM node:4.4
COPY src /opt/app
CMD ["node", "/opt/app/webBasar/bin/www"]

#start docker daemon
#eval "$(docker-machine env default)"

#ip de la docker machine : 192.168.99.100

#le container s'appelle res/apache-php
#docker build -t res/node-express .

#docker run -d -p 9090:3000 res/node-express

#lancer un bash du container
#docker exec -it nom_du_container /bin/bash

#stopper un container
#docker kill nom_du_container

#docker run -d -p 9090:3000 res/node-express

#192.168.99.100
